### PR TITLE
fix: isolate PostgREST features from supabase-js

### PR DESCRIPTION
**Pull request by soedirgo**
Currently, some of postgrest-js's functionalities are implemented in supabase-js, like [select](https://github.com/supabase/supabase-js/blob/33939998516e9325e207a63a8a3f10463e89aa41/src/index.js#L137) and [order](https://github.com/supabase/supabase-js/blob/33939998516e9325e207a63a8a3f10463e89aa41/src/index.js#L177). This causes a mismatch of the implementations between the two, which caused https://github.com/supabase/postgrest-js/issues/84.

Since supabase-js is made to act like postgrest-js, we should implement PostgREST-related features solely on postgrest-js and expose that from supabase-js through prototypal inheritance.

I manually tested this on a new Supabase project, but there's some problem with the test suite so I couldn't get them to pass. Will address it in a separate PR.

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hey @soedirgo , just want to check on this with respect to the fork you've got in your personal account.

Should I review this, or should I wait until you have finished what you're working on?

**Comment by soedirgo** [comment]
I'm only working on postgrest-js at the moment, so it should be OK to review. I think what blocked me was some failing tests in https://github.com/supabase/supabase-js/issues/14 (probably an outdated Docker image).

**Comment by soedirgo** [comment]
Forgot to mention, if this gets merged, things like filters/`order`/etc. before `select` will break once the new postgrest-js gets released, so better put it on hold I think. Old code should work unless we update postgrest-js's minor version in this repo.

**Comment by kiwicopple** [comment]
OK we're going to hold off merging this until your signal Bobbie - I guess we will close this in favour of your postgrest-js changes

**Comment by soedirgo** [comment]
👍 I also wanted to make some changes to this PR in light on the change on postgrest-js. I'll draft this for now and reopen once it's ready.

**Comment by soedirgo** [comment]
Superseded by #50.

**Pull request closed without merging**
