### PR TITLE
fix: bump gotrue-js/next version

### PR DESCRIPTION
**Pull request by kangmingtay**

### CODE REVIEW

**Review by alaister — CHANGES_REQUESTED** [review]
I think we'll need to update the `supabase-js` code that uses the now removed methods?

**Review by alaister — APPROVED** [review]
lgtm!
Can we also remove the `isBrowser()`? Not sure if it's still used anywhere?

**Review by alaister — CHANGES_REQUESTED** [review]
Oh also looks like the tests need changing to `getSession()` as well

**Comment by kangmingtay** [comment]
@alaister i think we can just remove them since they are using `setAuth` ?

**Review by alaister — APPROVED** [review]
@kangmingtay yep I agree – the use case is no longer relevant.

**Pull request merged**
