### PR TITLE
chore: type for optional params

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## What kind of change does this PR introduce?

just used a better way to define optional params instead of writing `undefined` explicitly

### CODE REVIEW

**Review by soedirgo — APPROVED** [review]
Looks good, thanks!

**Comment by Ananya2001-an** [comment]
Awesome...though a test is failing is it, because of my change? Probably not I hope :)

**Comment by soedirgo** [comment]
I don't think so - retrying

**Comment by soedirgo** [comment]
Looks good now, thanks again!

**Comment by Ananya2001-an** [comment]
Happy to help :)

**Pull request merged**
